#!/usr/bin/env bash
# Concatenate src/*.sh into the standalone dist/proxy-man.sh artifact.
set -euo pipefail

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
SRC_DIR="$ROOT_DIR/src"
DIST_DIR="$ROOT_DIR/dist"
OUTPUT="$DIST_DIR/proxy-man.sh"

shopt -s nullglob
modules=("$SRC_DIR"/*.sh)
shopt -u nullglob

if ((${#modules[@]} == 0)); then
  printf 'build: no source modules found in %s\n' "$SRC_DIR" >&2
  exit 1
fi

mkdir -p "$DIST_DIR"
tmp=$(mktemp "$DIST_DIR/.proxy-man.sh.XXXXXX")
cleanup() { rm -f "$tmp"; }
trap cleanup EXIT

{
  printf '%s\n' '#!/usr/bin/env bash'
  printf '%s\n' '# Generated by scripts/build.sh from src/*.sh — do not edit directly.'
  printf '\n'

  first=1
  for module in "${modules[@]}"; do
    if ((first)); then
      first=0
    else
      printf '\n'
    fi

    # Drop a leading shebang from modules so only the generated header keeps one.
    if IFS= read -r first_line < "$module" && [[ "$first_line" == '#!/'* ]]; then
      tail -n +2 "$module"
    else
      cat "$module"
    fi

    # Guarantee a newline after each module when the file has no trailing newline.
    if [[ -s "$module" && $(tail -c1 "$module" | wc -l) -eq 0 ]]; then
      printf '\n'
    fi
  done
} > "$tmp"

chmod 0755 "$tmp"
mv "$tmp" "$OUTPUT"
trap - EXIT

printf 'build: wrote %s (%s lines)\n' "$OUTPUT" "$(wc -l < "$OUTPUT")"
